### ISSUE TITLE
Mod resolution encountered an incompatible mod set!

### ISSUE THREAD

**Issue by TixRequiem** [FlashyReese/sodium-extra-fabric#199]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.16.5

### Sodium Extra version.

0.4.3

### Sodium version.

0.2.0+build.4

### What happened?

I do not know what to do, I have already reinstalled Java more than 9999 times, absolutely all versions, but nothing helps.

### Relevant logs

[06:23:03] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.4
[06:23:03] [main/WARN]: Mod resolution failed
[06:23:03] [main/INFO]: Immediate reason: [NEG_HARD_DEP sodium-extra 0.4.3 {breaks sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.0]}, ROOT_FORCELOAD_SINGLE sodium 0.2.0+build.4, ROOT_FORCELOAD_SINGLE sodium-extra 0.4.3]
[06:23:03] [main/INFO]: Reason: [NEG_HARD_DEP sodium-extra 0.4.3 {breaks sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.0]}, HARD_DEP caffeineconfig 1.0.0 {depends java @ [>=16]}]
[06:23:03] [main/INFO]: Fix: add [], remove [], replace [[sodium-extra 0.4.3] -> add:sodium-extra 1 ([(-?,?)])]
[06:23:03] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium Extra' (sodium-extra) 0.4.3 with any version that is compatible with:
		 - sodium 0.2.0+build.4
Unmet dependency listing:
	 - Mod 'Sodium Extra' (sodium-extra) 0.4.3 is incompatible with any 0.1.x version, version 0.2.0+IRIS_rev.400af47 or version 0.3.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.2.0+build.4!
	 - Mod 'CaffeineConfig' (caffeineconfig) 1.0.0 requires version 16 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]

### Additional information

![bd4bd2e34942e36bcea0c937cbd23b5a](https://user-images.githubusercontent.com/104876733/166612238-53f5deb3-4515-4ed5-8b11-440fa07aa818.png)

**Comment by FlashyReese** [comment]
Try using an older Fabric Loader `0.13.3` instead, I will try to get this fixed for the next release.

**Comment by TixRequiem** [comment]
Thanks.
