### ISSUE TITLE
Sodium Extra doesn't detect Fabric

### ISSUE THREAD

**Issue by CherryBones** [FlashyReese/sodium-extra-fabric#255]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.2

### Sodium Extra version.

0.4.10

### Sodium version.

1.19.2

### What happened?

Whenever I launch Minecraft, it automatically crashes because it tells me the version doesn't have Fabric installed. I do have Fabric Installed, as well as Sodium, Lithium and Iris, and whenever I remove Sodium Extra from the folder it launches perfectly. 

### Relevant logs

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Sodium Extra' (sodium-extra) 0.4.10+mc1.19.2-build.64 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Additional information

I currently have fabric 0.14.9 on the instance, and I'm using MultiMC

**Comment by FlashyReese** [comment]
You need to install [Fabric API](https://modrinth.com/mod/fabric-api)

**Comment by CherryBones** [comment]
> You need to install [Fabric API](https://modrinth.com/mod/fabric-api)

In the page of Sodium it says that it doesn't support Fabric Rendering API, so I thought it wouldn't be that because it'd just bug the other one. Am I misunderstanding something there?

**Comment by FlashyReese** [comment]
> > You need to install [Fabric API](https://modrinth.com/mod/fabric-api)
> 
> In the page of Sodium it says that it doesn't support Fabric Rendering API, so I thought it wouldn't be that because it'd just bug the other one. Am I misunderstanding something there?

Fabric API includes a bunch of APIs, Sodium Extra uses Fabric API's client lifecycle events API.
