### ISSUE TITLE
Unable to Launch Sodium Extra - Incompatible mod set!

### ISSUE THREAD

**Issue by AnotherJellyfish** [FlashyReese/sodium-extra-fabric#268]
```
PolyMC version: 1.3.2-404b9599


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.172.117.60, 18.172.117.47, 18.172.117.34, 18.172.117.46]

session.minecraft.net resolves to:
    [35.153.153.200, 100.24.172.95, 34.199.236.154]

textures.minecraft.net resolves to:
    [18.160.200.72, 18.160.200.11, 18.160.200.51, 18.160.200.107]

api.mojang.com resolves to:
    [18.160.225.73, 18.160.225.120, 18.160.225.124, 18.160.225.40]


Minecraft folder is:
C:/Users/Username/AppData/Roaming/PolyMC/instances/1.19.2/.minecraft


Java path is:
C:/Program Files/Java/jdk-17.0.4.1/bin/javaw.exe


Checking Java version...
Java is version 17.0.4.1, using amd64 architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/Username/AppData/Roaming/PolyMC/instances/1.19.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech-natives-windows/1.13.9/text2speech-natives-windows-1.13.9.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/net/fabricmc/fabric-loader/0.14.9/fabric-loader-0.14.9.jar
  C:/Users/Username/AppData/Roaming/PolyMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:

Mods:
  [✔️] iris-mc1.19.2-1.3.1
  [✔️] sodium-extra-0.4.11+mc1.19.2-build.68
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18

Params:
  --username  --version 1.19.2 --gameDir C:/Users/Username/AppData/Roaming/PolyMC/instances/1.19.2/.minecraft --assetsDir C:/Users/Username/AppData/Roaming/PolyMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx10112m, -Duser.language=en]


Minecraft process ID: 23156


[22:11:35] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[22:11:35] [main/WARN]: Mod resolution failed
[22:11:35] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE sodium-extra 0.4.11+mc1.19.2-build.68 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE sodium-extra 0.4.11+mc1.19.2-build.68]
[22:11:35] [main/INFO]: Reason: [HARD_DEP sodium-extra 0.4.11+mc1.19.2-build.68 {depends fabric @ [*]}]
[22:11:35] [main/INFO]: Fix: add [add:fabric 1 ([(-?,?)])], remove [], replace []
[22:11:35] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Sodium Extra' (sodium-extra) 0.4.11+mc1.19.2-build.68 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Process exited with code 1.
```
Using PolyMC, Fabric loader is installed as 0.14.9

**Comment by FlashyReese** [comment]
You need to install [Fabric API](https://modrinth.com/mod/fabric-api).
