### ISSUE TITLE
The game crashes when trying to enter the graphics settings menu. URGENTLY!

### ISSUE THREAD

**Issue by denny4-user** [FlashyReese/sodium-extra-fabric#318]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

fabric-loader-0.14.19-1.16.5

### Sodium Extra version.

sodium-extra-mod-fabric-1_16_5.jar

### Sodium version.

sodium-fabric-mc1.16.5-0.2.0+build.4.jar

### What happened?

I go into graphics settings and the game crashes. Tried to install new Java - did not help. The error is the same. All additional mods have been installed.

### Relevant logs

File: https://pastebin.com/QYup6H2h
ScreenShot: https://prnt.sc/q9dJNbqtLse2

---- Minecraft Crash Report ----
// Why did you do that?

Time: 30.04.23 18:23
Description: mouseClicked event handler

java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:43)
	at net.minecraft.class_310.handler$zbc000$boostedbrightness$openScreen(class_310.java:4894)
	at net.minecraft.class_310.method_1507(class_310.java)
	at net.minecraft.class_429.handler$ble000$sodium$open(class_429.java:1023)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$4137/995364892.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4127/152533088.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4010/1752377596.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3248/686302915.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:43)
	at net.minecraft.class_310.handler$zbc000$boostedbrightness$openScreen(class_310.java:4894)
	at net.minecraft.class_310.method_1507(class_310.java)
	at net.minecraft.class_429.handler$ble000$sodium$open(class_429.java:1023)
	at net.minecraft.class_429.method_19828(class_429.java)
	at net.minecraft.class_429$$Lambda$4137/995364892.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4127/152533088.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_429
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4010/1752377596.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3248/686302915.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4006434752 bytes (3820 MB) / 4496293888 bytes (4288 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		artifice: Artifice 0.13.1+1.16.2-rc1
		autoclicker-fabric: Auto Clicker 1.16.5-1.0.2-build.12
		autoconfig1u: Auto Config v1 Updated 3.3.1
		baritone: Baritone 1.6.3
		betterf3: BetterF3 1.1.3
		bluemap: BlueMap 1.5.5
		blur: Blur (Fabric) 2.1.0
		boostedbrightness: Boosted Brightness 2.0.0
		caffeineconfig: CaffeineConfig 1.0.0
		chesttracker: Chest Tracker 0.8.13
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.14.64
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynamicfps: Dynamic FPS 2.0.2
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.14.19
		fiber: fiber 0.23.0-2
		io_github_douira_glsl-transformer: glsl-transformer 1.0.1
		iris: Iris 1.4.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lambdynlights: LambDynamicLights 1.3.4+1.16
		libgui: LibGui 3.3.5+1.16.5
		litematica: Litematica 0.0.0-dev.20210917.192300
		lithium: Lithium 0.6.6
		lowfire: Low Fire 1.16.5-1.1.0
		malilib: MaLiLib 0.10.0-dev.21+arne.8
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20210917.191825
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.23
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_anarres_jcpp: jcpp 1.4.14
		org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		phosphor: Phosphor 0.8.0
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.16.5-build.68
		resolutioncontrol: ResolutionControl+ 2.0.1
		satin: Satin 1.5.1
		shulkerboxtooltip: Shulker Box Tooltip 2.3.7+1.16.5
		slight-gui-modifications: 'Slight' GUI Modifications 1.5.1
		sodium: Sodium 0.2.0+build.4
		sodium-extra: Sodium Extra 0.4.13+mc1.16.5-build.73
		spruceui: SpruceUI 2.0.4+1.16
		tweakeroo: Tweakeroo 0.10.0-dev.20210917.191839
		whereisit: Where Is It 1.11.7
		worldedit: WorldEdit 7.2.5+57d5ac9
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 531.41, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: slightguimodifications:cts_textures, vanilla, Fabric Mods, file/Animated RGB Bar, file/Custom Font Template, file/Glowing Ores, file/Rainy Day, file/RedStone+
	Current Language: Русский (Россия)
	CPU: 12x Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz

**Comment by FlashyReese** [comment]
> at net.minecraft.class_310.handler$zbc000$boostedbrightness$openScreen(class_310.java:4894)

Seems like a boosted brightness issue.

**Comment by denny4-user** [comment]
WORK!) THANKS!<3

**Comment by denny4-user** [comment]
> > at net.minecraft.class_310.handler$zbc000$boostedbrightness$openScreen(class_310.java:4894)
> 
> Seems like a boosted brightness issue.

<3
