### ISSUE TITLE
Incompat with Immersive Portals on MC Fabric 1.19.3

### ISSUE THREAD

**Issue by Cape-City** [FlashyReese/sodium-extra-fabric#320]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.19.3

### Sodium Extra version.

sodium-extra-0.4.19+mc1.19.3-build.101.jar

### Sodium version.

sodium-fabric-mc1.19.3-0.4.11+build.25

### What happened?

MC could not start, 'coz your mod now needs Sodium 0.4.11 installed, but Immersive Portals needs 0.4.9 and won't update anymore for 1.19.3.

Sodium Extra
FlashyReese
sodium-extra-0.4.19+mc1.19.3-build.101.jar

Sodium
jellysquid3_
sodium-fabric-mc1.19.3-0.4.11+build.25

Immersive Portals
qouteall
immersive-portals-2.5.4-mc1.19.3-fabric.jar

Mod Menu
Prospector
modmenu-5.1.0-beta.4.jar

### Relevant logs

[07:59:20] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.19
[07:59:20] [main/WARN]: Mod resolution failed
[07:59:20] [main/INFO]: Immediate reason: [NEG_HARD_DEP immersive_portals 9.0 {breaks sodium @ [<0.4.9 || >0.4.9]}, ROOT_FORCELOAD_SINGLE immersive_portals 9.0, ROOT_FORCELOAD_SINGLE sodium 0.4.11+build.25]
[07:59:20] [main/INFO]: Reason: [NEG_HARD_DEP immersive_portals 9.0 {breaks sodium @ [<0.4.9 || >0.4.9]}]
[07:59:20] [main/INFO]: Fix: add [], remove [], replace [[immersive_portals 9.0] -> add:immersive_portals 1 ([(-?,?)])]
[07:59:20] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Portals' (immersive_portals) 9.0 with any version that is compatible with:
		 - sodium 0.4.11+build.25
Unmet dependency listing:
	 - Mod 'Immersive Portals' (immersive_portals) 9.0 is incompatible with any version before 0.4.9 or any version after 0.4.9 of mod 'Sodium' (sodium), but a matching version is present: 0.4.11+build.25!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]

**Comment by FlashyReese** [comment]
Not to offend you but I don't think I'm at fault here, I updated sodium extra to target the latest version for sodium 1.19.3. Your choices are to wait for IP to update or just downgrade sodium and sodium extra.
