### ISSUE TITLE
Conflicts With Particle Blocker

### ISSUE THREAD

**Issue by CodeF53** [FlashyReese/sodium-extra-fabric#332]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.4.20

### Sodium version.

0.4.10

### What happened?

World doesn't render, and logs are rapidly filled with `NullPointerException`s due to `"this.client.world" is null`

### Relevant log.

Full Log: https://mclo.gs/AmNP6Ir

<details>
	<summary>Relevant snippet (deobfuscated):</summary>

	[09:30:12] [Render thread/ERROR]: Error executing task on Client
	java.lang.NullPointerException: Cannot invoke "net.minecraft.client.world.ClientWorld.getChunkManager()" because "this.world" is null
		at net.minecraft.client.network.ClientPlayNetworkHandler.loadChunk(ClientPlayNetworkHandler.java:773) ~[client-intermediary.jar:?]
		at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkData(ClientPlayNetworkHandler.java:738) ~[client-intermediary.jar:?]
		at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket.java:45) ~[client-intermediary.jar:?]
		at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket.java:12) ~[client-intermediary.jar:?]
		at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	
	[09:30:12] [Render thread/ERROR]: Error executing task on Client
	java.lang.NullPointerException: Cannot invoke "net.minecraft.client.world.ClientWorld.setTime(long)" because "this.client.world" is null
		at net.minecraft.client.network.ClientPlayNetworkHandler.onWorldTimeUpdate(ClientPlayNetworkHandler.java:984) ~[client-intermediary.jar:?]
		at net.minecraft.network.packet.s2c.play.WorldTimeUpdateS2CPacket.apply(WorldTimeUpdateS2CPacket.java:38) ~[client-intermediary.jar:?]
		at net.minecraft.network.packet.s2c.play.WorldTimeUpdateS2CPacket.apply(WorldTimeUpdateS2CPacket.java:6) ~[client-intermediary.jar:?]
		at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

</details>

<details>
<summary>Relevant snippet (obfuscated):</summary>

	[09:40:22] [Render thread/ERROR]: Error executing task on Client
	java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
		at net.minecraft.class_634.method_38539(class_634.java:773) ~[client-intermediary.jar:?]
		at net.minecraft.class_634.method_11128(class_634.java:738) ~[client-intermediary.jar:?]
		at net.minecraft.class_2672.method_11528(class_2672.java:45) ~[client-intermediary.jar:?]
		at net.minecraft.class_2672.method_11054(class_2672.java:12) ~[client-intermediary.jar:?]
		at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

	[09:40:22] [Render thread/ERROR]: Error executing task on Client
	java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_29089(long)" because "this.field_3690.field_1687" is null
		at net.minecraft.class_634.method_11079(class_634.java:984) ~[client-intermediary.jar:?]
		at net.minecraft.class_2761.method_11872(class_2761.java:38) ~[client-intermediary.jar:?]
		at net.minecraft.class_2761.method_11054(class_2761.java:6) ~[client-intermediary.jar:?]
		at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
		at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
		at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]

</details>

### Mods:
```
- fabric-api 0.85.0+1.20.1
	|-- fabric-api-base 0.4.29+b04edc7a77
	|-- ...
	\-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
- fabricloader 0.14.21
- java 17
- minecraft 1.20.1
- mixintrace 1.1.1+1.17
- particle-blocker 1.1
- sodium 0.4.10+build.27
- sodium-extra 0.4.20+mc1.20-build.103
	|-- caffeineconfig 1.1.0+1.17
	\-- crowdin-translate 1.4+1.19.3
- stackdeobfuscator 1.3.2+fabric.4bca927
	\-- net_fabricmc_mapping-io 0.3.0
```
The crash also happens without `stackdeobfuscator` and `mixintrace`, I just added those to get the deobfuscated trace

### Extra
Does not require any config to occur, happens with defaults.

I saw in one other issue a mention that the two mods conflict, but if they "officially" conflict, you should add a `breaks` or `conflicts` field to your `fabric.mod.json`.

**Comment by CodeF53** [comment]
Mirror Issue: https://github.com/Declipsonator/Particle-Blocker/issues/8
