### ISSUE TITLE
Sodium extra crashes game with iris

### ISSUE THREAD

**Issue by piemanau** [FlashyReese/sodium-extra-fabric#34]
When I go to the video settings menu the game crashes

Logs: https://pastebin.com/gvb3qUtH

**Comment by DragonEggBedrockBreaking** [comment]
You need to use the latest commit of sodium extra.

**Comment by DragonEggBedrockBreaking** [comment]
(You use Iris so you probably know how to compile something yourself)

**Comment by notsatvrn** [comment]
Working with the latest commit, I would try that out to see if it's fixed.

**Comment by FlashyReese** [comment]
Yes I'm aware, I fixed it, just leaving this open so people don't spam it until official release hence the `pending release` label.

**Comment by Wyvest** [comment]
`[22:45:01] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: sodium-extra conflicts with {sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.x]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:201) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.3.jar:?]
	... 5 more`
How do I fix this? using iris and sodium extra

**Comment by FlashyReese** [comment]
That's doing it's job properly. You need to update to Iris 1.0.1(only available through the Iris Installer) to use this. Or you can download them directly from https://github.com/IrisShaders/Iris-Installer-Files/raw/master/1.16.5/Iris-Sodium.zip

**Comment by Wyvest** [comment]
> That's doing it's job properly. You need to update to Iris 1.0.1(only available through the Iris Installer) to use this. Or you can download them directly from https://github.com/IrisShaders/Iris-Installer-Files/raw/master/1.16.5/Iris-Sodium.zip

ah my bad

**Comment by piemanau** [comment]
> That's doing it's job properly. You need to update to Iris 1.0.1(only available through the Iris Installer) to use this. Or you can download them directly from https://github.com/IrisShaders/Iris-Installer-Files/raw/master/1.16.5/Iris-Sodium.zip

Where is the iris installer?

**Comment by DragonEggBedrockBreaking** [comment]
> Where is the iris installer?

https://irisshaders.net/download.html

**Comment by piemanau** [comment]
Thanks

**Comment by piemanau** [comment]
> Yes I'm aware, I fixed it, just leaving this open so people don't spam it until official release hence the `pending release` label.

@FlashyReese have you released the fix on CF?

**Comment by FlashyReese** [comment]
> > Yes I'm aware, I fixed it, just leaving this open so people don't spam it until official release hence the `pending release` label.
> 
> @FlashyReese have you released the fix on CF?

It's on the 0.3.2 release, you need to update Iris to <=1.0.1

**Comment by piemanau** [comment]
> > > Yes I'm aware, I fixed it, just leaving this open so people don't spam it until official release hence the `pending release` label.
> > 
> > 
> > @FlashyReese have you released the fix on CF?
> 
> It's on the 0.3.2 release, you need to update Iris to <=1.0.1

Update? that sounds like a downgrade xD

I will give it a go though

**Comment by piemanau** [comment]
Will you make it compatible with the newer ones aswell?

**Comment by FlashyReese** [comment]
> Will you make it compatible with the newer ones aswell?

Sorry my bad it's `>=1.0.1`. It should be compatible if Iris Sodium based off the official repository.
