### ISSUE TITLE
Beacon rainbow beams caused crash on Sodium Extra 0.4.24 and above

### ISSUE THREAD

**Issue by Nesquate** [FlashyReese/sodium-extra-fabric#342]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.4.24 and above

### Sodium version.

0.4.10

### What happened?

![2023-08-04_18 31 06](https://github.com/FlashyReese/sodium-extra-fabric/assets/49124428/8f772990-5f65-404d-bf82-a458ba35e5e1)
*Rainbow beams in my server*

When I saw beacon ranbow beams in my server, my client crashed and log wrote these:
```
[18:34:58] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering Block Entity
	at net.minecraft.class_824.method_3554(class_824.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:286) ~[sodium-fabric-mc1.20-0.4.10+build.27.jar:?]
	at net.minecraft.class_761.handler$dii000$sodium$onRenderTileEntities(class_761.java:12108) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1372) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.OutOfMemoryError: Out of stack space.
	at org.lwjgl.system.MemoryStack.nmalloc(MemoryStack.java:315) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.system.MemoryStack.nmalloc(MemoryStack.java:297) ~[lwjgl-3.3.1.jar:?]
	at net.minecraft.class_822.handler$dke000$sodium-extra$render(class_822.java:1553) ~[client-intermediary.jar:?]
	at net.minecraft.class_822.method_3541(class_822.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_822.method_3569(class_822.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	... 15 more
```

Seems this problem is related to #333, because after I downgraded to 0.4.23 and below, Client is not crashed again.

But error message is completely different.

I tried to disable all mods, leave Sodium and Sodium Extra enabled, this problem still exists.

### Relevant logs

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12259933/latest.log)
[crash-2023-08-04_18.34.58-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/12259934/crash-2023-08-04_18.34.58-client.txt)

**Comment by FlashyReese** [comment]
The problem is not related to #333, it's the immediate mode vertex stack running out of space. ~~Try updating to `0.4.26`, if the issue persist please let me know.~~

**Comment by FlashyReese** [comment]
Can you let me know if this build resolves your issue? [sodium-extra-0.4.26+mc1.20.1-342.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/12260422/sodium-extra-0.4.26%2Bmc1.20.1-342.zip)

**Comment by Nesquate** [comment]
> Can you let me know if this build resolves your issue? [sodium-extra-0.4.26+mc1.20.1-342.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/12260422/sodium-extra-0.4.26%2Bmc1.20.1-342.zip)

No, it doesn't work for me.  
This problem still exists.

I uploads these logs only Sodium, Sodium Extra and Fabric API are enabled, hope these logs can help you.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12262481/latest.log)
[crash-2023-08-04_23.56.57-client.txt](https://github.com/FlashyReese/sodium-extra-fabric/files/12262483/crash-2023-08-04_23.56.57-client.txt)

**Comment by FlashyReese** [comment]
Can you try this build instead? [sodium-extra-0.4.26+mc1.20.1-342-part2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/12264944/sodium-extra-0.4.26%2Bmc1.20.1-342-part2.zip)

The thing I can't replicate the issue while in a server with 4096 beacons running for ~6hrs but several other users have also reported this issue.

**Comment by Nesquate** [comment]
> Can you try this build instead? [sodium-extra-0.4.26+mc1.20.1-342-part2.zip](https://github.com/FlashyReese/sodium-extra-fabric/files/12264944/sodium-extra-0.4.26%2Bmc1.20.1-342-part2.zip)
> 
> The thing I can't replicate the issue while in a server with 4096 beacons running for ~6hrs but several other users have also reported this issue.

Yes, this build works well for me.  

This problem may be fixed, maybe need more other users to test.

**Comment by FlashyReese** [comment]
I made a release for it in `0.4.27`, it is temporarily disabled for `0.5.0`.
