### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by chrnogueira06** [FlashyReese/sodium-extra-fabric#37]
The mod crashing the game, not start

**Comment by FlashyReese** [comment]
Please provide a crash log, creating a issue just to say game crash doesn't help at all.

**Comment by chrnogueira06** [comment]
[03:21:49] [main/INFO]: Loading for game Minecraft 1.16.5
[03:21:49] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: sodium-extra conflicts with {sodium @ [0.1.x || 0.2.0+IRIS_rev.400af47 || >=0.3.x]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:219) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:216) ~[fabric-loader-0.11.6.jar:?]
	... 5 more

**Comment by FlashyReese** [comment]
If you are using Iris+Sodium please update Iris to 1.0.1 via the Iris Installer. If you are only using Sodium, please update Sodium to 0.2.0

**Comment by chrnogueira06** [comment]
Where do I download version 2.0?

**Comment by FlashyReese** [comment]
https://modrinth.com/mod/sodium
