### ISSUE TITLE
I can'tt open Minecraft!

### ISSUE THREAD

**Issue by youar10** [FlashyReese/sodium-extra-fabric#400]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.1

### Sodium version.

0.4.1

### What happened?

When I added the Sodium into the mod folder and then opened the game,the game didn't response.It keeped getting stuck loading the page.

![图片1](https://github.com/FlashyReese/sodium-extra-fabric/assets/175010922/a4d2ba18-8378-4ad7-9a25-9c62c75365c5)

I can't find the reason.What's the problem?

![图片3](https://github.com/FlashyReese/sodium-extra-fabric/assets/175010922/9a265acb-9152-4683-9d88-61b2b7d8e7eb)

And this is the mod folder.

![图片2](https://github.com/FlashyReese/sodium-extra-fabric/assets/175010922/af5fc46f-b51f-4ab0-b6d0-03e80cc08c1c)

### Relevant logs

[authlib-injector] [INFO] Logging file: F:\系统默认\桌面\Minecraft\.minecraft\versions\1.18.2\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil/
[18:18:06] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.15.11
[18:18:07] [ForkJoinPool-1-worker-1/WARN]: Mod lottweaks uses the version 2.3.2a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '2a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:18:07] [main/WARN]: Warnings were found!
 - 模组 'Sodium Extra' (sodium-extra) 0.4.1 建议安装 reeses-sodium-options 的 1.4.1 及以上版本，但没有安装它！
	 - 为了最佳体验，您应该安装 reeses-sodium-options 的 1.4.1 及以上版本。
[18:18:07] [main/INFO]: Loading 71 mods:
	- brrp_v1 1.0.1
	- fabric-api 0.77.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.13+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.15+b4f4f6cd60
	   |-- fabric-rendering-v1 1.11.0+b7f3cf3460
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- iris 1.6.6
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- journeymap-fabric 5.9.8
	   \-- journeymap-api-fabric 1.18.2-1.9-fabric-SNAPSHOT
	- jsblock 2.0.0-beta-2+1.18.2
	- lithium 0.10.3
	- londonunderground 2.2.0
	- londonundergroundtrains 1.0.0
	- lottweaks 2.3.2a
	   \-- reach-entity-attributes 2.1.1
	- minecraft 1.18.2
	- mishanguc 1.2.7
	- mtr 4.0.0-beta-8
	- phosphor 0.8.1
	- sodium 0.4.1+build.15
	   \-- org_joml_joml 1.10.2
	- sodium-extra 0.4.1
	   \-- caffeineconfig 1.0.0
	- worldedit 7.2.10+1742f98
[18:18:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/%e7%b3%bb%e7%bb%9f%e9%bb%98%e8%ae%a4/%e6%a1%8c%e9%9d%a2/Minecraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:18:08] [main/INFO]: Compatibility level set to JAVA_17
[18:18:09] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 0 override(s) found
[18:18:09] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[18:18:10] [main/INFO]: Loaded configuration file for Sodium Extra: 25 options available, 0 override(s) found
[18:18:11] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[18:18:11] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[18:18:11] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[18:18:12] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[18:18:13] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[18:18:34] [Render thread/INFO]: sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod sodium-extra->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[authlib-injector] [INFO] Httpd is running on port 9886
[authlib-injector] [INFO] Transformed [net.minecraft.class_742] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[18:18:36] [Render thread/INFO]: Environment: authHost='https://littleskin.cn/api/yggdrasil/authserver', accountsHost='http://127.0.0.1:9886/https/api.mojang.com', sessionHost='http://127.0.0.1:9886/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:9886/https/api.minecraftservices.com', name='PROD'
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[18:18:36] [Render thread/INFO]: Setting user: 铁粉123
[authlib-injector] [INFO] Transformed [net.minecraft.class_3248] with [Username Character Check Transformer]
[18:18:38] [Render thread/INFO]: Initializing ServerSide Packet Registries
[18:18:38] [Render thread/INFO]: [JCM] Joban Client Mod v2.0.0 Beta-2
[18:18:38] [Render thread/INFO]: [JCM] Hello MTR 4.0.0-beta-8+1.18.2
[18:18:40] [Render thread/INFO]: Registering MTR London Underground Addon blocks
[18:18:40] [Render thread/INFO]: Registering MTR London Underground Addon block entity types
[18:18:40] [Render thread/INFO]: Registering MTR London Underground Addon creative mode tabs
[18:18:40] [Render thread/INFO]: Registering MTR London Underground Addon sound events
[18:18:40] [Render thread/INFO]: Minecraft Mappings logging enabled
[18:18:40] [Render thread/INFO]: Minecraft Mappings logging enabled
[18:18:52] [Render thread/INFO]: :  __  __     _                                                __    _     
[18:18:52] [Render thread/INFO]: : |  \/  |   (_)    _ _      ___     __       _ _   __ _      / _|  | |_   
[18:18:52] [Render thread/INFO]: : | |\/| |   | |   | ' \    / -_)   / _|     | '_| / _` |    |  _|  |  _|  
[18:18:52] [Render thread/INFO]: : |_|__|_|  _|_|_  |_||_|   \___|   \__|_   _|_|_  \__,_|   _|_|_   _\__|  
[18:18:52] [Render thread/INFO]: : _|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""| 
[18:18:52] [Render thread/INFO]: : "`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' 
[18:18:52] [Render thread/INFO]: :   _____                                     _      _                     
[18:18:52] [Render thread/INFO]: :  |_   _|    _ _   __ _    _ _      ___     (_)    | |_                   
[18:18:52] [Render thread/INFO]: :    | |     | '_| / _` |  | ' \    (_-<     | |    |  _|                  
[18:18:52] [Render thread/INFO]: :   _|_|_   _|_|_  \__,_|  |_||_|   /__/_   _|_|_   _\__|                  
[18:18:52] [Render thread/INFO]: : _|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|                 
[18:18:52] [Render thread/INFO]: : "`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'                 
[18:18:52] [Render thread/INFO]: :    ___              _       _                      _  _                  
[18:18:52] [Render thread/INFO]: :   | _ \   __ _     (_)     | |   __ __ __ __ _    | || |                 
[18:18:52] [Render thread/INFO]: :   |   /  / _` |    | |     | |   \ V  V // _` |    \_, |                 
[18:18:52] [Render thread/INFO]: :   |_|_\  \__,_|   _|_|_   _|_|_   \_/\_/ \__,_|   _|__/                  
[18:18:52] [Render thread/INFO]: : _|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_| """"|                 
[18:18:52] [Render thread/INFO]: : "`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-' (4.0.0-beta-8+1.18.2) 
[18:18:52] [Render thread/INFO]: :                                                                          
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway blocks
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway items
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway block entity types
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway entity types
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway creative mode tabs
[18:18:53] [Render thread/INFO]: Registering Minecraft Transit Railway sound events
[18:18:53] [Render thread/INFO]: Minecraft Mappings logging enabled
[18:18:55] [Render thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@283a23a0]
[18:18:55] [Render thread/INFO]: WorldEdit for Fabric (version 7.2.10+1742f98) is loaded
[18:18:55] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[18:18:56] [Render thread/INFO]: [JCM] Loading client config...
[18:18:57] [Render thread/INFO]: Registering Minecraft Transit Railway key bindings
[18:18:58] [Render thread/INFO]: Resource pack version check completed in 2 ms
[18:18:58] [ForkJoinPool.commonPool-worker-2/WARN]: [Iris Update Check] Cached update file detected, using that!
[18:18:58] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:19:00] [Render thread/INFO]: Debug functionality is disabled.
[18:19:00] [Render thread/INFO]: DSA support not detected.
[18:19:00] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[18:19:00] [Render thread/INFO]: Shaders are disabled
[18:19:00] [Render thread/INFO]: BRRP register - before vanilla
[18:19:00] [Render thread/INFO]: BRRP register - after vanilla
[18:19:01] [Render thread/INFO]: BRRP register - before user
[18:19:02] [Render thread/INFO]: Hardware information:
[18:19:02] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
[18:19:02] [Render thread/INFO]: GPU: Intel(R) HD Graphics 4000 (Supports OpenGL 3.2.0 - Build 10.18.10.4252)
[18:19:02] [Render thread/INFO]: OS: Windows 10 (10.0)
[18:19:05] [Render thread/INFO]: Narrator library for x64 successfully loaded
[18:19:05] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Better Runtime Resource Pack (BRRP) v1, CaffeineConfig, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Iris, Journeymap, Joban Client Mod, Lithium, MTR London Underground Addon, MTR London Underground Trains, LotTweaks, Mishang Urban Construction, Minecraft Transit Railway, Phosphor, Reach Entity Attributes, Sodium, Sodium Extra, WorldEdit)
[18:19:05] [Render thread/INFO]: BRRP register - before vanilla
[18:19:05] [Render thread/INFO]: BRRP register - after vanilla
[18:19:05] [Worker-Main-4/WARN]: File londonunderground:sounds/northernline/this_south_wimbledon_terminates_morden.ogg does not exist, cannot add it to event londonunderground:sw_mdn
[18:19:05] [Worker-Main-4/WARN]: File londonunderground:sounds/northernline/tootingbroadway_terminates.ogg does not exist, cannot add it to event londonunderground:tb_terminates
[18:19:05] [Worker-Main-4/WARN]: File londonunderground:sounds/northernline/sw_chx_highb.ogg does not exist, cannot add it to event londonunderground:sw_chx_highb
[18:19:05] [Worker-Main-4/WARN]: File londonunderground:sounds/northernline/arrival.ogg does not exist, cannot add it to event londonunderground:arrival
[18:19:05] [Worker-Main-4/WARN]: File londonunderground:sounds/northernline/next_southwimbledon.ogg does not exist, cannot add it to event londonunderground:next_southwimbledon
[18:19:06] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[18:19:06] [Render thread/INFO]: Initializing ClientSide Packet Registries
[18:19:06] [Render thread/INFO]: No plugins for JourneyMap API discovered.
[18:19:08] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:19:08] [Render thread/INFO]: JourneyMap log initialized.
[18:19:08] [Render thread/INFO]: initialize ENTER
[18:19:09] [Render thread/INFO]: [ClientAPI] built with JourneyMap API 1.9-SNAPSHOT
[18:19:09] [Render thread/INFO]: Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[18:19:09] [Render thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[18:19:10] [Render thread/ERROR]: Couldn't get resource set from null to null: java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "fileLocation" is null
[18:19:11] [Render thread/INFO]: Preloaded theme textures: 0
[18:19:12] [Render thread/INFO]: initialize EXIT, elapsed count 1 avg 5892.24ms
[18:19:12] [Render thread/INFO]: postInitialize EXIT, elapsed count 1 avg 32.17ms
[18:19:19] [ForkJoinPool.commonPool-worker-1/ERROR]: 
java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:534) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:639) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at org.mtr.mod.Patreon.openConnectionSafe(Patreon.java:80) ~[MTR-fabric-4.0.0-beta-8+1.18.2.jar:?]
	at org.mtr.mod.Patreon.openConnectionSafeJson(Patreon.java:91) ~[MTR-fabric-4.0.0-beta-8+1.18.2.jar:?]
	at org.mtr.mod.Patreon.lambda$getPatreonList$3(Patreon.java:50) ~[MTR-fabric-4.0.0-beta-8+1.18.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/platform_tfl_gap
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/platform_tfl_island
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a4
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a5
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a6
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/british_rail_underground
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/platform_tfl_gap
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a6b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a5b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a4b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a1b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in minecraft:item/panels/sw_advert2
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in minecraft:item/panels/sw_advert3
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in minecraft:item/panels/sw_advert4
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a6
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a4
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:block/station_a5
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/british_rail_underground
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/platform_tfl_island
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a1b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a5b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a4b
[18:19:34] [Worker-Main-5/WARN]: Unable to resolve texture reference: #missing in londonunderground:item/station_a6b
[18:19:35] [Worker-Main-5/WARN]: Texture minecraft:block/sign/st2 with size 1000x669 limits mip level from 3 to 0
[18:19:35] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 3 to 0, because of minimum power of two: 1

**Comment by 7777777-4547** [comment]
### About logs
If you want to copy to comment please use:
``````md
```log
 <copy log to here>
```
``````
Otherwise, you can send the log file in comment.

### Issue reply
This log seems not all, have you tried disabling sodium extra mod and relaunching it?
If it still happens, you should maybe try going to another mod's issue report and closing this issue.
