### ISSUE TITLE
1.21.1 incompatibility with Radium Reforged

### ISSUE THREAD

**Issue by amzelee** [FlashyReese/sodium-extra-fabric#409]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.21.1

### Sodium Extra version.

0.6.0-beta.1

### Sodium version.

0.6.0-beta.1

### What happened?

Crash upon launch.

### Relevant logs

- [Latest Log](https://mclo.gs/zLGrUh9)

### Additional information

[Radium Reforged github issue](https://github.com/Reforged-Hub/radium-upstream/issues/38) that I also posted for reference.

**Comment by Texbio** [comment]
Exception caught from launcher
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Module sodium_extra contains package net.caffeinemc.caffeineconfig, module NanoLiveConfig exports package net.caffeinemc.caffeineconfig to sodium_extra
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:806)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.(Configuration.java:139)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:54)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:101)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
... 5 more
Exiting with ERROR

**Comment by FlashyReese** [comment]
Radium Reforged compatibility is unsupported, and there are no plans to support this compatibility target. Closing as not planned.
