### ISSUE TITLE
Can't launch in minecraft 1.16.5 with fabric 0.12.3

### ISSUE THREAD

**Issue by Xiaoqianghepipi** [FlashyReese/sodium-extra-fabric#91]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.16.5

### Sodium Extra version.

0.3.2

### Sodium version.

0.2.0

### What happened?

my game caused by this mod

### Relevant logs

[19:29:15] [main/INFO]: Loading for game Minecraft 1.16.5
[19:29:15] [main/ERROR]: A critical error occurred
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:124) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:124) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:199) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183) [fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119) [fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.3.jar:?]
Caused by: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at H:\PCL\.minecraft\versions\1.16.5-Fabric 0.12.3\mods\sodium-extra-0.3.2.jar: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=0.3.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.readDependenciesContainer(V1ModMetadataParser.java:471) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:163) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:160) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:123) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:52) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:265) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:206) ~[fabric-loader-0.12.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_60]
Caused by: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=0.3.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser.parse(VersionPredicateParser.java:65) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.util.version.VersionPredicateParser.parse(VersionPredicateParser.java:105) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.api.metadata.version.VersionPredicate.parse(VersionPredicate.java:51) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModDependencyImpl.<init>(ModDependencyImpl.java:39) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.readDependenciesContainer(V1ModMetadataParser.java:469) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.V1ModMetadataParser.parse(V1ModMetadataParser.java:163) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:160) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.readModMetadata(ModMetadataParser.java:123) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.metadata.ModMetadataParser.parseMetadata(ModMetadataParser.java:52) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:265) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.12.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:206) ~[fabric-loader-0.12.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_60]

### Additional information

![2](https://user-images.githubusercontent.com/68947244/139428571-5c3ed9a9-273f-427c-9b74-d10eeec4b011.PNG)
![1](https://user-images.githubusercontent.com/68947244/139428576-094c9c64-d76e-416e-aeda-dc2ab0c55534.PNG)
![3](https://user-images.githubusercontent.com/68947244/139428581-8ab2c206-9997-43ea-bb07-0fccb2c08f57.PNG)

**Comment by lacafjh** [comment]
I had a similar crash report log, and my versions are totally the same as yours except the Fabric version (0.12.4).

I tried to disable all mods in the above game version except Fabric API, Mod menu, Sodium and Sodium Extra, and it still crashes when starting the game.

I have uploaded [latest.log](https://paste.ee/p/5zlN1).

These two lines of logs may be helpful.

> Caused by: net.fabricmc.loader.impl.metadata.ParseMetadataException: Error reading fabric.mod.json file for mod at \my\game\path\.minecraft\versions\1.16.5-Fabric\mods\sodium-extra-0.3.2.jar: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=0.3.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!
> 
> Caused by: net.fabricmc.loader.api.VersionParsingException: Invalid predicate: >=0.3.x, version ranges with wildcards (.X) require using the equality operator or no operator at all!

Here is the list of my mods

![image](https://user-images.githubusercontent.com/21212113/140390648-6772aae6-275a-4f32-935e-40ca011d1a28.png)

**Comment by FlashyReese** [comment]
There are some changes on Fabric Loader after `0.12.0` when dealing with version handling, you can either downgrade Fabric Loader to `0.11.7` or remove the version locked that's loaded inside the jar in `fabric.mod.json`

I will push a hotfix some time this weekend if you don't want to do neither of those.

**Comment by lacafjh** [comment]
Thanks for your help, that worked! Some of the other mods will no longer be available after rolling back the Fabric Loader version though, so I'm looking forward to the fix you released over the weekend as well. Again, thank you for the extra features that made Sodium so convenient!

**Comment by FlashyReese** [comment]
You can now find the release on GitHub Releases section, if you are looking for the video options changes it can be found [here](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options/files/3517163).
